# Generated by Django 4.1.2 on 2022-11-09 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trener', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('day', models.DateField()),
                ('trening_type', models.CharField(max_length=50)),
                ('col', models.IntegerField()),
                ('is_was', models.BooleanField()),
                ('progul', models.BooleanField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fitclub.sportgroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('day', models.IntegerField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fitclub.sportgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(to='fitclub.sportgroup')),
            ],
        ),
    ]
