# Generated by Django 4.1.2 on 2022-12-14 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='e-mail')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Описание')),
                ('value', models.IntegerField(verbose_name='Сумма')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Доход',
                'verbose_name_plural': 'Доходы',
            },
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150, verbose_name='Ключ')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='Значение')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Описание')),
                ('value', models.IntegerField(verbose_name='Сумма')),
                ('spend_type', models.CharField(max_length=150, verbose_name='Тип')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.CreateModel(
            name='SportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('trener', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Trening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(verbose_name='Начало')),
                ('end', models.TimeField(verbose_name='Конец')),
                ('day', models.DateField(verbose_name='Дата')),
                ('trening_type', models.CharField(max_length=50, verbose_name='Тип занятия')),
                ('col', models.IntegerField(verbose_name='Кол. участников')),
                ('is_was', models.BooleanField(verbose_name='Было ли занятие')),
                ('progul', models.BooleanField(verbose_name='Прогул')),
                ('clients', models.ManyToManyField(blank=True, to='fitclub.client', verbose_name='Участники')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fitclub.sportgroup', verbose_name='Группа')),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper_for_training', to=settings.AUTH_USER_MODEL, verbose_name='Помощник')),
                ('trener', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='royal_trainer', to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Занитие',
                'verbose_name_plural': 'Занятия',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('accure', models.IntegerField(blank=True)),
                ('give', models.IntegerField(verbose_name='Выплачено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_trainer', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Зарплаты',
            },
        ),
        migrations.CreateModel(
            name='Peyment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.CharField(max_length=150, verbose_name='Способ оплаты')),
                ('pay_type', models.CharField(max_length=150, verbose_name='Тип оплаты')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('value', models.IntegerField(verbose_name='Сумма')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitclub.client', verbose_name='Ученик')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fitclub.sportgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='GroupTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(verbose_name='Начало')),
                ('end', models.TimeField(verbose_name='Конец')),
                ('day', models.IntegerField(verbose_name='День недели')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fitclub.sportgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Время занятий',
                'verbose_name_plural': 'Время занятий',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='groups',
            field=models.ManyToManyField(to='fitclub.sportgroup', verbose_name='Группы'),
        ),
    ]
