# Generated by Django 4.1.2 on 2023-03-27 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitclub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название зала')),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='zal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='fitclub.zal', verbose_name='Зал'),
        ),
        migrations.AddField(
            model_name='peyment',
            name='zal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='fitclub.zal', verbose_name='Зал'),
        ),
        migrations.AddField(
            model_name='salary',
            name='zal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='fitclub.zal', verbose_name='Зал'),
        ),
        migrations.AddField(
            model_name='spending',
            name='zal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='fitclub.zal', verbose_name='Зал'),
        ),
    ]
