# Generated by Django 4.1.2 on 2022-11-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trening',
            name='clients',
            field=models.ManyToManyField(blank=True, null=True, to='fitclub.client'),
        ),
    ]
