# Generated by Django 4.1.2 on 2022-11-24 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitclub', '0002_trening_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='trening',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper_for_training', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trening',
            name='trener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='royal_trainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trening',
            name='clients',
            field=models.ManyToManyField(blank=True, to='fitclub.client'),
        ),
    ]
