# Generated by Django 4.1.2 on 2023-03-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitclub', '0002_zal_income_zal_peyment_zal_salary_zal_spending_zal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zal',
            options={'verbose_name': 'Зал', 'verbose_name_plural': 'Залы'},
        ),
    ]
