# Generated by Django 4.1.2 on 2023-09-14 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitclub', '0003_alter_zal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportgroup',
            name='age',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='sportgroup',
            name='wcount',
            field=models.IntegerField(default=None, null=True, verbose_name='Желаемое кол. участников'),
        ),
        migrations.AddField(
            model_name='sportgroup',
            name='zal',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitclub.zal', verbose_name='Группа'),
        ),
    ]
