# Generated by Django 4.1.2 on 2022-11-28 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitclub', '0003_trening_helper_trening_trener_alter_trening_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trening',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fitclub.sportgroup'),
        ),
    ]
