# Generated by Django 4.1.2 on 2022-11-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitclub', '0005_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
